### ISSUE TITLE
The best lap doesn't seems to be saved

### ISSUE THREAD

**Issue by dannyhpy** [JerryMalmstrom/Drifters#2]
It stays at 0.00 for me

**Comment by JerryMalmstrom** [comment]
Hi

Thank you for your issue.
Do you mean the numbers on the left side of the screen?

If so, that is the "local best time", and i know that doesnt update.
I will fix that direct, i neglected that number when i focused on the online laptimes...

**Comment by dannyhpy** [comment]
Oh I see, thank you, your game is cool to play, continue the good work :slightly_smiling_face:

**Comment by JerryMalmstrom** [comment]
Fixed now.
